export const internet_culture = 'internet_culture'
export const digital_economics = 'digital_economics'
export const technology_and_politics ='technology_and_politics'
export const technology_and_society = 'technology_and_society'
export const human_computer_interaction = 'human_computer_interaction'
export const cognitive_science = 'cognitive_science'
export const technical_posts = 'technical_posts'
export const philosophy = 'philosophy'
export const software_industry = 'software_industry'
export const general = 'general'

